### ISSUE TITLE
rails5

### ISSUE THREAD

**Issue by elfassy** [kern/minitest-reporters#168] opened 2015-07-23 20:09 UTC
I can't get it to work with the master branch of rails (rails 5.0.0.alpha). There is just no color.
Anyone else have this problem?

**Comment by os97673** [comment] 2015-07-24 05:50
I (almost) do not use rails and thus I have not seen these problems.  But I'm ready to fix them as soon as you will provide a simple repo to reproduce the problem.

**Comment by elfassy** [comment] 2015-07-30 01:16
Here you go: https://github.com/elfassy/minitest_reporter_rails5

**Comment by os97673** [comment] 2015-07-31 15:37
I've just cloned the repo, "bundle install", "rake test" and everything works ok :(
What have I missed?

**Comment by elfassy** [comment] 2015-07-31 19:59
did you get color and ProgressReporter to work?

**Comment by os97673** [comment] 2015-07-31 20:28
Oops, I've expected exception (thought that this is another ticket :(
No I see the problem.  The real problem is that minitest-reporters are not used at all.

**Comment by os97673** [comment] 2015-08-02 19:23
Filed rails/rails#21102.  Will see response of rails developers.

**Comment by os97673** [comment] 2015-08-03 19:16
rails/rails#21105 has been merged thus the problem should be fixed

**Comment by elfassy** [comment] 2015-08-04 13:54
Thanks @os97673 
Unfortunately that rails fix doesn't see to do it for me. I've updated the example code. It's still giving me the same result (reporters are not used). Did you get the test app to work on your end?

**Comment by os97673** [comment] 2015-08-04 15:40
You are right, it looks like I need to do some other changes too (I had modified version of the test project and minitest-reporters)

**Comment by os97673** [comment] 2015-08-11 07:50
I've created #171 with possible fix for the problem.  Could you please try one and let me know if it works for you?

**Comment by jonatack** [comment] 2015-08-13 21:12
Thanks @os97673 for looking at this. FWIW I just tried it using #171 with Rails 5 (`gem 'minitest-reporters', github: 'kern/minitest-reporters', branch: 'rails5-support'`) and the reporter is not being used.

**Comment by os97673** [comment] 2015-08-14 07:41
@jonatack please provide the test project which demonstrates the problem.  The test provided by @elfassy with the branch works fine for me. (btw make sure you have up-to-date rails5 and you have stopped spring before the testing)

**Closed** 2015-08-17 12:05 UTC
