### ISSUE TITLE
Minitest 5.11.1 regression for SpecReporter.

### ISSUE THREAD

**Issue by skunkworker** [kern/minitest-reporters#248] opened 2018-01-05 07:55 UTC
On Minitest `5.10.3` spec reporter grouped the specs under the test file name,
like
``` 
FooTest
   test_bar       PASS
   test_ack       PASS
```
but after updating Minitest to `5.11.1`, they are now not grouped under the test file name, like
``` 
FooTest
   test_bar       PASS

FooTest
   test_ack       PASS
```

**Comment by alexhayes** [comment] 2018-01-11 20:21
I can confirm a similar issue for the RubyMine reporter and rolling back to minitest 5.10.3 fixes the 
issue.

![image](https://user-images.githubusercontent.com/142916/34845481-145037c4-f769-11e7-9a0d-18f4ee515aa0.png)

**Comment by donnfelker** [comment] 2018-01-12 00:57
I can also confirm. I'm having the same problem as @alexhayes in RubyMine. This question is also showing up on Stackoverflow now too. https://github.com/kern/minitest-reporters/issues/248

**Comment by mbround18** [comment] 2018-01-12 23:45
I can confirm this as well, I believe the issue stems from how [minitest](https://github.com/seattlerb/minitest) changed the contents of what gets passed into the `record` method.

**Comment by sandstrom** [comment] 2018-01-22 14:38
I think [this is the line](https://github.com/seattlerb/minitest/commit/00433fc0a4fdd0e6b302aace633384ba13122376#diff-efcebb0b0e7d5c021792f400fd891d9fR581) that prints it. But it seems like it has been there all along, so I can't really figure out why the issue occurred now.

**Comment by os97673** [comment] 2018-02-03 05:49
should be fixed by 53ef519fcad7a61c5bb4340be92b4697dca34739 and released as 1.2.0.beta1

**Closed by os97673** 2018-02-03 05:49 UTC

**Comment by mattbrictson** [comment] 2018-03-20 00:18
Will 1.2.0 be released soon? 🙏

**Comment by os97673** [comment] 2018-03-21 23:30
published

**Comment by tleish** [comment] 2018-05-02 18:05
@os97673 - The problem might not be minitest-reporters, it looks like something changed with minitest, which is affecting the reporter and the way in which Rubymine uses it.  To test this, you can use minitest-reporters project. 

Running the minitest-reporters project inside Rubymine using _minitest 5.10.3_, the report outputs as expected.

```diff
- s.add_dependency 'minitest', '>= 5.0'
+ s.add_dependency 'minitest', '5.10.3'
```
minitest-reporters (1.3.0.beta2)

![image](https://user-images.githubusercontent.com/1099993/39540594-1ef9f3fa-4e11-11e8-91a6-f9ed670dece1.png)

However, running the minitest-reporters project inside Rubymine using _minitest 5.11.0_ or greater, the report outputs a nested fashion and appears to give warnings also (in yellow).

```diff
- s.add_dependency 'minitest', '>= 5.0'
+ s.add_dependency 'minitest', '>= 5.11.0'
```
minitest-reporters (1.3.0.beta2)

![image](https://user-images.githubusercontent.com/1099993/39540375-76c97c46-4e10-11e8-8c89-76f1b55c588e.png)



According to a ticket filed with Jetbrains/Rubymine, it was suggested that the issue is with minitest-reporters.
see: https://youtrack.jetbrains.com/issue/RUBY-20717#u=1525269631250

**Comment by os97673** [comment] 2018-05-02 18:29
I have commented on the ticket hope RubyMine team will reopen it or will provide more information about the problem in rubymine-reporters.

**Comment by tleish** [comment] 2018-05-03 05:30
You likely saw in the other forum, but I narrowed down the minitest commit that broke the reporters to https://github.com/seattlerb/minitest/commit/00433fc0a4fdd0e6b302aace633384ba13122376

I also opened a issue there to see if someone might be able to help identify why https://github.com/seattlerb/minitest/issues/759
