### ISSUE TITLE
minitest-reporters v1.1 fails with RubyMine 7.1

### ISSUE THREAD

**Issue by gpr** [kern/minitest-reporters#179] opened 2015-09-14 13:28 UTC
When executing the `rake test` command with RubyMine the following issue occurs (see https://github.com/gpr/rubymine_minitest_reporters_11_issue):

```
/home/user/.rvm/rubies/ruby-2.2.2/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /home/user/workspace/rubymine_minitest_reporters_11_issue/bin/spring rake test
Testing started at 15:19 ...
Started

/home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-reporters-1.1.0/lib/minitest/reporters/rubymine_reporter.rb:82:in `before_suite': undefined method `create_suite_started' for nil:NilClass (NoMethodError)
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-reporters-1.1.0/lib/minitest/reporters/base_reporter.rb:20:in `before_test'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-reporters-1.1.0/lib/minitest/reporters/rubymine_reporter.rb:90:in `before_test'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-reporters-1.1.0/lib/minitest/reporters.rb:46:in `block in run_with_hooks'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-reporters-1.1.0/lib/minitest/reporters.rb:46:in `each'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-reporters-1.1.0/lib/minitest/reporters.rb:46:in `run_with_hooks'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-5.8.0/lib/minitest.rb:781:in `run_one_method'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-5.8.0/lib/minitest.rb:308:in `run_one_method'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-5.8.0/lib/minitest.rb:296:in `block (2 levels) in run'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-5.8.0/lib/minitest.rb:295:in `each'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-5.8.0/lib/minitest.rb:295:in `block in run'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-5.8.0/lib/minitest.rb:334:in `on_signal'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-5.8.0/lib/minitest.rb:321:in `with_info_handler'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-5.8.0/lib/minitest.rb:294:in `run'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-5.8.0/lib/minitest.rb:155:in `block in __run'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-5.8.0/lib/minitest.rb:155:in `map'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-5.8.0/lib/minitest.rb:155:in `__run'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-5.8.0/lib/minitest.rb:129:in `run'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/minitest-5.8.0/lib/minitest.rb:56:in `block in autorun'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/spring-1.4.0/lib/spring/application.rb:156:in `fork'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/spring-1.4.0/lib/spring/application.rb:156:in `serve'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/spring-1.4.0/lib/spring/application.rb:131:in `block in run'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/spring-1.4.0/lib/spring/application.rb:125:in `loop'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/spring-1.4.0/lib/spring/application.rb:125:in `run'
	from /home/user/.rvm/gems/ruby-2.2.2@rubymine_minitest_reporters_11_issue/gems/spring-1.4.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

Process finished with exit code 1
Empty test suite.
```

**Comment by os97673** [comment] 2015-09-14 18:46
duplicate of #175

**Closed by os97673** 2015-09-14 18:46 UTC

**Comment by gpr** [comment] 2015-09-15 10:48
Thanks!
