### ISSUE TITLE
undefined method `gsub' for #<Object:0x00000001edb218> (NoMethodError)

### ISSUE THREAD

**Issue by dmitrym0** [kern/minitest-reporters#223] opened 2016-12-06 00:10 UTC
Hello minitest-reporters friends,

Occasionally my test suite will fail with the above error, and here's the stack trace:

```
/var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-reporters-1.1.13/lib/minitest/reporters/spec_reporter.rb:46:in `record_print_status': undefined method `gsub' for #<Object:0x00000001edb218> (NoMethodError)
	from /var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-reporters-1.1.13/lib/minitest/reporters/spec_reporter.rb:31:in `record'
	from /var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-reporters-1.1.13/lib/minitest/minitest_reporter_plugin.rb:21:in `block in record'
	from /var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-reporters-1.1.13/lib/minitest/minitest_reporter_plugin.rb:20:in `each'
	from /var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-reporters-1.1.13/lib/minitest/minitest_reporter_plugin.rb:20:in `record'
	from /var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-5.10.1/lib/minitest.rb:674:in `block in record'
	from /var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-5.10.1/lib/minitest.rb:673:in `each'
	from /var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-5.10.1/lib/minitest.rb:673:in `record'
	from /var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-hooks-1.4.0/lib/minitest/hooks/test.rb:97:in `rescue in with_info_handler'
	from /var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-hooks-1.4.0/lib/minitest/hooks/test.rb:68:in `with_info_handler'
	from /var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-5.10.1/lib/minitest.rb:308:in `run'
	from /var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-5.10.1/lib/minitest.rb:158:in `block in __run'
	from /var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-5.10.1/lib/minitest.rb:158:in `map'
	from /var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-5.10.1/lib/minitest.rb:158:in `__run'
	from /var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-5.10.1/lib/minitest.rb:135:in `run'
	from /var/autotest/vendor/bundle/ruby/2.1.0/gems/minitest-5.10.1/lib/minitest.rb:62:in `block in autorun'
```

I patched line 46 so that we check that the object supports `gsub` (basically a `return unless test.name.class.public_instance_methods.include?(:gsub)`). 

The interesting thing I see now when the test suite runs is this:

```
BookTest
Running setup...
Tearing down

BookTest
Running setup...
Setup done...
Tearing down
  test_book_was_successfully_created_and_opened                   PASS (17.66s)
```

You'll notice that the second paragraph has a setup, teardown and the result. But the first paragraph only has a setup and then a teardown (an `after_all`). Does this then imply that the setup has failed in the first paragraph and that's possibly why the test didn't run and the original exception was thrown because there was no successful test?

**Comment by os97673** [comment] 2016-12-06 02:11
Hmm, I cannot reproduce the problem :(  It looks like I'm missing some tiny but important detail :(
Could you please provide a small test which reproduce the problem?

**Comment by dmitrym0** [comment] 2016-12-08 00:36
Hi Oleg,

I can't consistently reproduce the problem either in my test suite. I suspected that having failing assertions in `setup` or `before_all` was the reason for this issue so I created a small test, but I can't reproduce it. 

Looking at stack, why would `test` object's `name` be anything other than a string?

**Comment by os97673** [comment] 2016-12-08 00:56
it looks like you are using minitest-hooks and they could add something to the picture.

**Comment by milep** [comment] 2017-01-12 20:47
Got the same error, without reporters I get exception:
```
Selenium::WebDriver::Error::ElementNotVisibleError: element not visible
```

**Comment by os97673** [comment] 2017-01-22 08:57
@milep are you sure the error you see somehow related to the issue?

**Comment by milep** [comment] 2017-01-22 09:01
@os97673 Other exceptions causes it too. I have the minitest-hooks also. Might be that if the exception is raised in the `before(:all)` block.

**Comment by os97673** [comment] 2017-01-22 09:02
do you have simple repo to reproduce the problem?

**Comment by milep** [comment] 2017-01-22 09:14
I tried with minutest-hooks repository, added to `spec/helper.rb`:
```
require "minitest/reporters"
Minitest::Reporters.use! Minitest::Reporters::SpecReporter.new
```
Then the around specs started to fail. But I'm not 100% sure it's related this

**Comment by dmitrym0** [comment] 2017-08-10 14:52
I just found this issue again (after googling). I have no recollection of creating it! 😮 

In any case, I'll try to spend some time trying to reproduce it. Intermittent test failures are annoying.

**Comment by os97673** [comment] 2017-11-22 04:41
Need test to reproduce the problem.

**Comment by os97673** [comment] 2018-08-31 01:52
Closing since no test has been provided.  Feel free to reopen with the test.

**Closed by os97673** 2018-08-31 01:52 UTC
Labels: test-needed
