### ISSUE TITLE
Tests appear as "terminated" in RubyMine 2018.3.1

### ISSUE THREAD

**Issue by toncid** [kern/minitest-reporters#263] opened 2018-06-04 08:38 UTC
Hello,

For some reason, even though all test passed, RubyMine shows the test run as "terminated":

<img width="808" alt="minitest-terminated" src="https://user-images.githubusercontent.com/1837897/40907123-1df22c34-67e3-11e8-9500-7aecd7c241d8.png">

There are no errors or stack traces in the log.

How can I gather more information to find out what went wrong?

**Comment by toncid** [comment] 2018-06-04 08:41
A bit more info: https://youtrack.jetbrains.com/issue/RUBY-20717#u=1515471194920

**Comment by os97673** [comment] 2018-06-04 16:37
according to the ticket the problem is caused by changes in minitest and Rubymine team is working on this (https://youtrack.jetbrains.com/issue/RUBY-21353) I will be happy to help them as soon as they will have something.
Since I have nothing to do here I'm closing the issue for now.

**Closed by os97673** 2018-06-04 16:37 UTC

**Comment by toncid** [comment] 2018-06-20 13:34
Is this issue related to #266?
